package main

import (
	"fmt"
	"sync"
	"time"
)

type RateLimiter struct {
	ticker   *time.Ticker
	requests chan struct{}
}

func NewRateLimiter(rate time.Duration) *RateLimiter {
	rl := &RateLimiter{
		ticker:   time.NewTicker(rate),
		requests: make(chan struct{}),
	}
	
	go rl.run()
	return rl
}

func (rl *RateLimiter) run() {
	for range rl.ticker.C {
		select {
		case rl.requests <- struct{}{}:
			// Token available
		default:
			// Channel full, skip this token
		}
	}
}

func (rl *RateLimiter) Allow() bool {
	select {
	case <-rl.requests:
		return true
	default:
		return false
	}
}

func (rl *RateLimiter) Stop() {
	rl.ticker.Stop()
	close(rl.requests)
}

func worker(id int, limiter *RateLimiter, wg *sync.WaitGroup) {
	defer wg.Done()
	
	for i := 0; i < 5; i++ {
		if limiter.Allow() {
			fmt.Printf("Worker %d: request %d allowed at %v\n", 
				id, i+1, time.Now().Format("15:04:05.000"))
		} else {
			fmt.Printf("Worker %d: request %d rate limited\n", id, i+1)
		}
		time.Sleep(100 * time.Millisecond)
	}
}

func main() {
	// Allow 2 requests per second
	limiter := NewRateLimiter(500 * time.Millisecond)
	defer limiter.Stop()
	
	wg := sync.WaitGroup{}
	
	fmt.Println("Starting rate limiter (2 requests/second)")

	// Start multiple workers trying to make requests
	for i := 1; i <= 3; i++ {
		wg.Add(1)
		go worker(i, limiter, &wg)
	}

	wg.Wait()
	fmt.Println("Rate limiting demonstration completed")
}

### How to Explain in Interview (Spoken style format)

**Interviewer:** How do you implement a rate limiter using channels?

**Your Response:** I implement a rate limiter using a ticker that generates tokens at a fixed rate and a channel that stores available tokens. The ticker creates a new token every 500ms, representing the allowed request rate.

The Allow method checks if a token is available using a non-blocking select. If a token is available, the request proceeds; if not, it's rate limited. This creates a token bucket pattern where tokens are generated at a fixed rate and consumed by requests.

Multiple workers can call Allow simultaneously, but only the number of tokens generated by the ticker will be allowed. This provides smooth rate limiting across multiple goroutines.

The key insight is that channels naturally model the token bucket algorithm - the ticker generates tokens, the channel stores them, and select provides non-blocking consumption. This pattern is essential for API rate limiting, preventing system overload, and controlling resource usage in concurrent systems.
