// Java 14 Feature Demonstration Program

// Java 14 introduced Records as a Preview Feature.
// Records are special classes used to create immutable data objects
// and automatically generate constructors, getters, toString(), equals(), and hashCode().

record User(String name, int age) {
}

public class Java14_Features {

    public static void main(String[] args) {

        // Creating an object of Record class
        User user = new User("Dhruv", 25);

        // toString() method is automatically generated by Record
        System.out.println("Record toString(): " + user);

        // Accessing Record fields using automatically generated getter methods
        System.out.println("Record Getter name(): " + user.name());
        System.out.println("Record Getter age(): " + user.age());

        // Java 14 introduced Switch Expressions (Final Feature)
        // It allows returning values directly from switch cases using '->'
        int day = 3;

        String result = switch (day) {
            case 1 -> "Monday";
            case 2 -> "Tuesday";
            case 3 -> "Wednesday";
            default -> "Other Day";
        };

        System.out.println("Switch Expression Output: " + result);

        // Helpful NullPointerExceptions
        // Java 14 improves NullPointerException messages to clearly show
        // which variable was null during the error.

        System.out.println("Java 14 Features: Records (Preview), Switch Expressions, Helpful NullPointerExceptions.");
    }
}